# Generated by Django 5.0.6 on 2024-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('theme_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Themes',
            },
        ),
    ]
